### ISSUE TITLE
Set monday as first day of week

### ISSUE THREAD

**Issue by unbreak** [jimcamut/calendarize#1]
Is there any easy way to setup that monday will be first day of week, not sunday?

**Comment by griffon-zgz** [comment]
> Is there any easy way to setup that monday will be first day of week, not sunday?


Yes, you have to modify "calendarize.js" to change the order of the day's name and skipLength in month.


Replace this:
`//var dayNames = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"]; --> Start on sunday.`
For this:
`var dayNames = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"]; --> Start on monday.`

And this:
`var skipLength = daysInMonth[0].getDay();`
For this:
`var skipLength = daysInMonth[0].getDay() - 1 == -1 ? 6 : daysInMonth[0].getDay() - 1;`

**Comment by jimcamut** [comment]
@unbreak and @griffon-zgz glad to see someone using this! And yes, @griffon-zgz's solution seems like a good bet, although I haven't used this plugin in a while.

**Comment by unbreak** [comment]
@griffon-zgz Thanks :)
@jimcamut This script is great! 👍
