### ISSUE TITLE
Start week with monday

### ISSUE THREAD

**Issue by darmar** [jimcamut/calendarize#2]
Hi,
could you help me a bit? What needs to be changed to render months with weeks starting with Monday?

Thank you,
regards

**Comment by jimcamut** [comment]
Good question, @darmar - see the solution here: https://github.com/jimcamut/calendarize/issues/1#issuecomment-387407048.

I haven't tried it myself, but without diving back into the code it seems like it should do the trick. Keep me posted if that works for you!

**Comment by darmar** [comment]
Yup, that did the trick :)
Thanks @jimcamut !
